[package]
name = "json-program"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
sp1-zkvm = { workspace = true }
jwt-rustcrypto = { workspace = true }
lib = { path = "../lib", package = "json-lib" }
